name: Test Deploy

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]


jobs:

  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: List contents of workspace directory
        run: ls -l /github/workspace
      - name: Navigate to project directory
        run: cd Vivimos
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start server
        run: nohup node index.js &
    # Install Cypress dependencies and run the tests.
      - name: Install Cypress Dependencies
      # Change the directory to the cypress folder.
        run: cd ./cypress && npm ci

      - name: Run Cypress tests
      # Change the directory to the cypress folder.
        run: cd ./cypress && npm run test

  deploy:
    needs: cypress_tests

    runs-on:
      ubuntu-latest
    steps:
      - name: Doing a deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Deploying to the server"
            source /root/.nvm/nvm.sh
            nvm use v20.12.2
            echo "Checking node and npm versions"
            node -v
            npm -v
            cd /var/www/Vivimos
            git pull
            rm -r cypress
            cd /var/www/Vivimos/frontend
            npm ci
            npm run build
            cd /var/www/Vivimos/Server
            rm -r dist
            mv /var/www/Vivimos/frontend/dist .
            pm2 delete vivimos
            pm2 start --name vivimos "dotnet run"
            